[package]
name = "lisp"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.1.5"
chumsky = "0.9.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

